
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  # MySQL Configuration
  datasource:
    url: ${DATABASE_URL} # credentials for database
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    # generate the logs from SQL statements via Hibernate
    show-sql: true
    # just update the db when the application starts; create missing schemas
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  sql:
#    init:
#      mode: always

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG

server:
  port: 8080
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /api/